/*
 * This file is auto-generated by generate_header.py script in the pokeemerald directory (not the one in the gba folder)
 * Do not edit manually.
 */

#ifndef GENERATED_SYMBOLS_H
#define GENERATED_SYMBOLS_H

#define RAM_SCRIPT_ADDR 0x0203CF68
#endif // GENERATED_SYMBOLS_H
