/*
 * This file is auto-generated by generate_header.py script.
 * Do not edit manually.
 */

#ifndef GENERATED_SYMBOLS_H
#define GENERATED_SYMBOLS_H

#define SAVE_BLOCK_1 0x02025A00
#define SAVE_BLOCK_2 0x02024A54
#define SAVE_BLOCK_3 0x02029808
#define SAVE_BLOCK_1_PTR 0x03005D8C
#define LOAD_GAME_SAVE 0x081534D1
#define AGB_MAIN 0x080003A5
#define RELOAD_SAVE 0x081700F9
#define LOAD_PLAYER_PARTY 0x08076DD5
#endif // GENERATED_SYMBOLS_H
